# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/site-id')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/site-id')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_id', to='sites.Site')),
            ],
        ),
    ]
